import type { ThemeConfig } from 'antd';

export const reaccionVitalTheme: ThemeConfig = {
  token: {
    colorPrimary: '#C62828',
    colorPrimaryHover: '#B71C1C',
    colorPrimaryActive: '#991B1B',
    colorLink: '#C62828',
    colorLinkHover: '#B71C1C',
    colorSuccess: '#2E7D32',
    colorWarning: '#F9A825',
    colorError: '#D32F2F',
    colorInfo: '#2563EB',
    colorText: '#1E293B',
    colorTextSecondary: '#64748B',
    colorBgLayout: '#F8FAFC',
    colorBgContainer: '#ffffff',
    colorBorder: '#E2E8F0',
    colorBorderSecondary: '#E2E8F0',
    borderRadius: 7,
    borderRadiusLG: 9,
    boxShadow: '0 1px 2px rgba(15, 23, 42, 0.05)',
    boxShadowSecondary: '0 2px 6px rgba(15, 23, 42, 0.06)',
    fontFamily:
      'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: 15,
    controlHeight: 40,
    controlHeightLG: 44,
    lineHeight: 1.5,
    padding: 16,
    paddingLG: 24,
    margin: 16,
    marginLG: 24,
  },
  components: {
    Layout: {
      bodyBg: '#F8FAFC',
      headerBg: '#ffffff',
      siderBg: '#ffffff',
    },
    Menu: {
      itemBg: '#ffffff',
      subMenuItemBg: '#ffffff',
      itemColor: '#475569',
      itemHoverBg: '#F8FAFC',
      itemHoverColor: '#1E293B',
      itemSelectedBg: '#FFF5F5',
      itemSelectedColor: '#C62828',
      itemBorderRadius: 6,
      itemHeight: 42,
    },
    Button: {
      primaryShadow: 'none',
      dangerShadow: 'none',
      defaultShadow: 'none',
      fontWeight: 600,
    },
    Card: {
      boxShadow: 'none',
      headerBg: '#ffffff',
    },
    Table: {
      headerBg: '#F1F5F9',
      headerColor: '#334155',
      headerSplitColor: '#E2E8F0',
      rowHoverBg: '#F8FAFC',
    },
    Input: {
      activeBorderColor: '#C62828',
      hoverBorderColor: '#B71C1C',
      activeShadow: '0 0 0 2px rgba(198, 40, 40, 0.10)',
    },
    Select: {
      activeBorderColor: '#C62828',
      hoverBorderColor: '#B71C1C',
      activeOutlineColor: 'rgba(198, 40, 40, 0.10)',
    },
    Modal: {
      titleFontSize: 18,
    },
    Typography: {
      titleMarginBottom: 0,
    },
  },
};
